apiVersion: v1
kind: Namespace
metadata:
  name: nfs-test
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
  namespace: nfs-test
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
kind: Pod
apiVersion: v1
metadata:
  name: test-pod
  namespace: nfs-test
  annotations:
    # NOTE - ignore the linter
    ignore-check.kube-linter.io/run-as-non-root: "need root to mount NFS server"
spec:
  containers:
  - name: test-pod
    image: gcr.io/google_containers/busybox:1.24
    command:
      - '/bin/sh'
    args:
      - '-c'
      - 'touch /mnt/SUCCESS && exit 0 || exit 1'
    volumeMounts:
      - name: nfs-pvc
        mountPath: '/mnt'
    resources:
      requests:
        memory: 64Mi
        cpu: 250m
      limits:
        memory: 128Mi
        cpu: 500m
    securityContext:
      readOnlyRootFilesystem: true
  restartPolicy: 'Never'
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: test-claim
