apiVersion: v1
kind: Namespace
metadata:
  name: gitea
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea
  labels:
    app: gitea
  annotations:
    # NOTE - ignore the linter
    ignore-check.kube-linter.io/run-as-non-root: "need root to mount NFS server"
    ignore-check.kube-linter.io/no-read-only-root-fs: "need /root write permission"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: gitea/gitea:1.15.0
          ports:
            - containerPort: 3000
              name: gitea
            - containerPort: 22
              name: git-ssh
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m
---
kind: Service
apiVersion: v1
metadata:
  name: gitea
  namespace: gitea
spec:
  selector:
    app: gitea
  ports:
    - name: gitea-http
      port: 3000
    - name: gitea-ssh
      port: 22
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea
  namespace: gitea
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: gitea.cmjserv.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitea
                port:
                  number: 3000
